sudo:  required
services:
        - docker

before_install:
        - docker build -t vpmaddur/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true vpmaddur/react-test npm test -- --coverage

after_success:
        - docker build -t vpmaddur/multi-client ./client
        - docker build -t vpmaddur/multi-nginx ./nginx
        - docker build -t vpmaddur/multi-server ./server
        - docker build -t vpmaddur/multi-worker ./worker
        # Log in to docker CLI

        - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin

        # Push Images into Repository

        - docker push vpmaddur/multi-client
        - docker push vpmaddur/multi-nginx
        - docker push vpmaddur/multi-server
        - docker push vpmaddur/multi-worker 

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "multi-docker"
        env: "MultiDocker-env"
        bucket_name: "elasticbeanstalk-us-east-2-380706206106"
        bucket_path: "docker-multi"
        on:
                branch: master
        access_key_id:
                secure: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY

